services:
  db:
    image: postgres
    restart: always
    ports:
      - 54329:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_database
