apiVersion: 1

datasources:
  - name: Prometheus
    uid: 'prometheus'
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: false

  - name: Tempo
    type: tempo
    access: proxy
    url: http://grafana-tempo:3200
    editable: false
    jsonData:
      streamingEnabled:
        search: true
        metrics: true
      # Enable Service Graph
      serviceMap:
        datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true
