@startuml
!define EP_INFRAPURPLE #4a00b8
!define EP_BORDER #404261

skinparam actorStyle awesome

package "VIDIS" as vidis {
    component "VIDIS Keycloak" as keycloak
    component "VIDIS Angebots-API" as angebotsapi
}

component "Landes-API" as land
component "Angebot" as angebot

package "Provisionierung" as provisionierung {
    database "Database" as db
    component "Provisionierung API" as api
    component "Provisionierung UI" as ui
    
    api --> db: Speichern der Freigaben
}

provisionierung -[hidden]u--> vidis

ui -> api: abrufen und verändern
angebot -u-> keycloak: Authentifizierung
angebot --l-> api: Schulstrukturdaten abrufen
api -u-> keycloak: Access Token validieren
api -u-> angebotsapi: AVV sicherstellen
api ---> land: Schulstrukturdaten abrufen



@enduml